### PR TITLE
Updating apiary

### PR DESCRIPTION
**Pull request by tjarosz**
Updated decks resources and response codes.

### CODE REVIEW

**Comment by VanDavv** [comment]
Well, that's strange situation, @mlotysz can You merge it? It's some Apiary - GitHub integration problem, as I see it.

**Comment by mlotysz** [comment]
Resolve conflicts first, please. Rebase onto master and create new pull request?

**Comment by tjarosz** [comment]
Fixed.

**Comment by mlotysz** [comment]
@tjarosz prosiłem nie o merge ale o rebase. Proszę o nowego PR.

**Pull request closed without merging**
