### PR TITLE
Adding author (his email) into deck.

### PR DESCRIPTION
**Pull request by ArekArek**

### CODE REVIEW

**Comment by tjarosz** [comment]
Everything seems to be correct, but we have "usersDecks" table in database. Is it still needed if we have information about user in deck's model?

**Comment by ArekArek** [comment]
I think table "usersDecks" isn't necessary, what do you think about it @VanDavv ?

**Comment by VanDavv** [comment]
I really don't like this solution. Why do we need 'email' field in deck entity? There should be a separate table for audit fields, it shouldn't bother main entity.

**Comment by mlotysz** [comment]
We need to be elastic in DB model. We have two entities: Deck and User. There is relationship between them (Deck is owned by a User). We have two problems to solve:
- how to create REST API to manage this relationship?
- how to save this relation in DB?

Let's start with DB first. I see 2. solutions here:
- add new property Decks.ownerId (FK to User table)
- add table DeckOwnership (deckId, userId)

REST side:
- we don't expect to change often ownership so maybe when we create Deck set ownerId with authenticated user and for "public" decks use null in ownerId? (BTW we could remove isPublic useless flag then.) We have to hide that field from JSON and prevent modification for it.

This PR must be closed and new one should be created. Thanks!

**Pull request closed without merging**
